server:
  port: 10500


spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1d69ea8a-0ead-4501-b37c-399b305fdd77
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: route_11
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: route_after
          uri: https://baidu.com
          predicates:
            - After=2020-12-29T16:08:00.864+08:00[Australia/Perth]
            - Query=url,after
            - RemoteAddr=192.168.1.4/24
            - Path=/order

        # 商品服务
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            #          将 /api 的请求路径用/替换，商品服务就可以通过
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 第三方服务
        - id: three_part_route
          uri: lb://mall-three-part
          predicates:
            - Path=/api/threepart/**
          filters:
            - RewritePath=/api/threepart/(?<segment>.*), /$\{segment}

        # 后台服务
        - id: admin_route
#          lb 代表负载均衡
          uri: lb://mall-admin
          predicates:
            - Path=/api/**   # 主文件目录写在后面，只有当不匹配 /api/product/** 或 /api/order/** 等路径的时候，才匹配其他的 /api/**
          filters:   # 网关过滤器GatewayFilter Factories
#            重写路径：将 /api 的路径用 /mall-admin 路径代替
            - RewritePath=/api/(?<segment>.*), /mall-admin/$\{segment}

