alibaba:
  cloud:
    access-key: *
    secret-key: *
    oss:
      endpoint: *
      bucket: *


server:
  port: 10600

spring:
  application:
    name: mall-three-part
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

